databases:
  - name: ns-shift-db
    plan: free
    databaseName: ns_shift
    user: ns_shift

services:
  - type: web
    plan: free
    name: ns-shift-web
    runtime: python
    buildCommand: "./build.sh build"
    startCommand: "./build.sh start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ns-shift-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
