databases:
  - name: ns-shift-db
    plan: basic-256mb
    region: singapore
    databaseName: ns_shift
    user: ns_shift

services:
  - type: web
    plan: starter 
    name: ns-shift-web
    runtime: python
    region: singapore
    buildCommand: "bash ./build.sh build"
    startCommand: "bash ./build.sh start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ns-shift-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "1"
      - key: ORTOOLS_NUM_SEARCH_WORKERS
        value: "1"
      - key: GUNICORN_TIMEOUT
        value: "210"
      - key: DJANGO_ALLOWED_HOSTS
        value: "ns-shift.com,www.ns-shift.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://ns-shift.com,https://www.ns-shift.com"
