# Generated by Django 5.2.6 on 2026-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffregulardayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='ability_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1：1年目・自立なし'), (2, '2：基本業務が自立'), (3, '3：新人指導が可能'), (4, '4：重症患者対応が可能'), (5, '5：管理代行業務が可能')], default=2, verbose_name='能力評価'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='job',
            field=models.CharField(choices=[('nurse', '看護師'), ('care_worker', '介護士')], default='nurse', max_length=20, verbose_name='職種'),
        ),
    ]
