# Generated by Django 5.2.6 on 2026-07-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shiftrule_required_leader_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftresult',
            name='shift_type',
            field=models.CharField(choices=[('day', '日勤'), ('night', '夜勤'), ('after_night', '明け'), ('off', '休み'), ('off_request', '希望休'), ('paid_leave', '有給'), ('special_leave', '特別休暇'), ('training', '研修')], max_length=20, verbose_name='勤務区分'),
        ),
        migrations.AlterField(
            model_name='shiftrule',
            name='required_leader_staff',
            field=models.IntegerField(default=0, verbose_name='必要リーダー人数'),
        ),
    ]
