# Generated by Django 5.2.6 on 2026-07-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_shiftresult_shift_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='対象日')),
                ('required_day_staff', models.IntegerField(blank=True, null=True, verbose_name='必要日勤人数')),
                ('required_night_staff', models.IntegerField(blank=True, null=True, verbose_name='必要夜勤人数')),
                ('required_leader_staff', models.IntegerField(blank=True, null=True, verbose_name='必要リーダー人数')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_rules', to='shifts.shiftplan')),
            ],
            options={
                'db_table': 'date_shift_rules',
                'ordering': ['target_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('shift_plan', 'target_date'), name='unique_date_shift_rule_shift_plan_target_date')],
            },
        ),
        migrations.CreateModel(
            name='WeekdayShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], verbose_name='曜日')),
                ('required_day_staff', models.IntegerField(blank=True, null=True, verbose_name='必要日勤人数')),
                ('required_night_staff', models.IntegerField(blank=True, null=True, verbose_name='必要夜勤人数')),
                ('required_leader_staff', models.IntegerField(blank=True, null=True, verbose_name='必要リーダー人数')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shift_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_rules', to='shifts.shiftplan')),
            ],
            options={
                'db_table': 'weekday_shift_rules',
                'ordering': ['shift_plan_id', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('shift_plan', 'day_of_week'), name='unique_weekday_shift_rule_shift_plan_day_of_week')],
            },
        ),
    ]
