# Generated by Django 5.2.6 on 2026-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_dateshiftrule_weekdayshiftrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateshiftrule',
            name='min_ability_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1：1年目・自立なし'), (2, '2：基本業務が自立'), (3, '3：新人指導が可能'), (4, '4：重症患者対応が可能'), (5, '5：管理代行業務が可能')], null=True, verbose_name='必要最低勤務レベル'),
        ),
        migrations.AddField(
            model_name='dateshiftrule',
            name='min_ability_level_staff_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='必要人数'),
        ),
        migrations.AddField(
            model_name='weekdayshiftrule',
            name='min_ability_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1：1年目・自立なし'), (2, '2：基本業務が自立'), (3, '3：新人指導が可能'), (4, '4：重症患者対応が可能'), (5, '5：管理代行業務が可能')], null=True, verbose_name='必要最低勤務レベル'),
        ),
        migrations.AddField(
            model_name='weekdayshiftrule',
            name='min_ability_level_staff_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='必要人数'),
        ),
    ]
