# Generated by Django 5.2.6 on 2026-07-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_dateshiftrule_min_ability_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftplan',
            name='title',
        ),
    ]
