# Generated by Django 5.2.6 on 2026-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_shiftcarryover_shiftresult_lock_reason'),
        ('staff', '0005_staffmember_is_holiday_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftplan',
            name='excluded_staffs',
            field=models.ManyToManyField(blank=True, related_name='excluded_shift_plans', to='staff.staffmember'),
        ),
    ]
