# Generated by Django 5.2.6 on 2026-08-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_shiftplan_excluded_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayshiftrule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日'), (7, '祝日')], verbose_name='曜日・祝日'),
        ),
    ]
