# Generated by Django 5.2.6 on 2026-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0010_alter_weekdayshiftrule_day_of_week"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialIPBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(max_length=64, unique=True)),
                (
                    "blocked_until",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="ブロック終了日時",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "db_table": "trial_ip_blocks",
            },
        ),
        migrations.CreateModel(
            name="TrialGenerationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="試行日時")),
            ],
            options={
                "db_table": "trial_generation_attempts",
                "indexes": [
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="trial_attempt_ip_created_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrialGenerationQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("session", "Session"), ("ip", "IP"), ("global", "全体")],
                        max_length=10,
                    ),
                ),
                ("scope_key", models.CharField(max_length=64)),
                ("date", models.DateField(verbose_name="対象日")),
                ("generation_count", models.PositiveIntegerField(default=0, verbose_name="生成回数")),
                (
                    "last_generation_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="最終生成日時",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
            options={
                "db_table": "trial_generation_quotas",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key", "date"),
                        name="unique_trial_generation_quota_scope_date",
                    )
                ],
            },
        ),
    ]
