# Generated by Django 5.2.6 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0012_remove_trial_attempt_and_ip_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialgenerationquota",
            name="generation_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="生成開始日時"),
        ),
    ]
